### ISSUE TITLE
Chrome 67.0.3396.99 - Extension doesn't work anymore

### ISSUE THREAD

**Issue by UnSimpleGeek** [aghorler/History-Disabler-for-Chromium#2]
Hi ! Since the new Chrome update (67), the extension doesn't work anymore and all my history is kept...

Are you aware about this issue ?

Thanks in advance for your answer.

**Comment by aghorler** [comment]
Hi, @UnSimpleGeek.

Version 2.0.2 of History Disabler deletes history as the tabs responsible for creating history items are closed. This is because the traditional method of deleting history as it is created was breaking the back/forward navigation functionality in Chrome 67.

History should still be deleted, just on tab close rather than instantly.

**Comment by UnSimpleGeek** [comment]
@aghorler Hi. I didn't understand that the new version of History Disabler deletes history this way now. Thanks for the quick answer.
